axon:
  axonserver:
    servers: localhost:8124
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.value}
server:
  port: 0
spring:
  application:
    name: cata-auth
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/cata_authorization
    username: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    security:
      BCrypt:
        secret: nemojPitiKavuNaPrazanZeludac
