version: '3'
services:
  database:
    image: 'postgres:12.2'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=cata_command,cata_history,cata_query
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  axonserver:
    image: 'axoniq/axonserver:4.3.3'''
    ports:
      - 8024:8024
      - 8124:8124

volumes:
  database-data: # named volumes can be managed easier using docker-compose
