spring:
  application:
    name: eureka-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
